<!DOCTYPE html>
	<html>
	    <head>
	      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    </head>
	    <body>
	      <p>Hola ${name},</p>
	      <p>Te invitamos a verificar tu perfil de REDI </p>
        <p>Puedes acceder a tu perfil REDI en el siguiente enlace </p>
        <p><a href="${URI}" target="_blank">${name}</a></p>
        <p><br/></p>

	      <p>Saludos,</p>
	      <p>
	        <em>REDI</em> <br />
	      </p>
	    </body>
	</html>